sudo: required
node_js:
  - "6"
install:
  - npm install
  - npm config set registry https://gcartifactory-us.jfrog.info/artifactory/api/npm/travisci-npm
  - curl -u$ARTIFACTIRY_USERNAME:$ARTIFACTORY_PASSWORD https://gcartifactory-us.jfrog.info/artifactory/api/npm/auth >> ~/.npmrc
  - npm publish --registry https://gcartifactory-us.jfrog.info/artifactory/api/npm/travisci-npm